var clover = new Object();

// JSON: {classes : [{name, id, sl, el,  methods : [{sl, el}, ...]}, ...]}
clover.pageData = {"classes":[{"el":189,"id":352,"methods":[{"el":30,"sc":3,"sl":28},{"el":35,"sc":3,"sl":32},{"el":41,"sc":3,"sl":37},{"el":52,"sc":3,"sl":50},{"el":59,"sc":3,"sl":54},{"el":70,"sc":3,"sl":68},{"el":81,"sc":3,"sl":72},{"el":92,"sc":3,"sl":90},{"el":96,"sc":3,"sl":94},{"el":100,"sc":3,"sl":98},{"el":104,"sc":3,"sl":102},{"el":109,"sc":3,"sl":106},{"el":120,"sc":3,"sl":118},{"el":131,"sc":3,"sl":129},{"el":142,"sc":3,"sl":140},{"el":153,"sc":3,"sl":151},{"el":164,"sc":3,"sl":162},{"el":171,"sc":3,"sl":169},{"el":176,"sc":3,"sl":173},{"el":187,"sc":3,"sl":185}],"name":"RipRoute","sl":23}]}

// JSON: {test_ID : {"methods": [ID1, ID2, ID3...], "name" : "testXXX() void"}, ...};
clover.testTargets = {"test_0":{"methods":[{"sl":106}],"name":"testDeterministic","pass":true,"statements":[{"sl":108}]},"test_1":{"methods":[{"sl":106}],"name":"testBasicTemplate","pass":true,"statements":[{"sl":108}]},"test_2":{"methods":[{"sl":106}],"name":"testDelete","pass":true,"statements":[{"sl":108}]},"test_4":{"methods":[{"sl":106}],"name":"testPost","pass":true,"statements":[{"sl":108}]},"test_5":{"methods":[{"sl":106}],"name":"testPut","pass":true,"statements":[{"sl":108}]},"test_6":{"methods":[{"sl":106}],"name":"testGet","pass":true,"statements":[{"sl":108}]}}

// JSON: { lines : [{tests : [testid1, testid2, testid3, ...]}, ...]};
clover.srcFileLines = [[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [2, 0, 1, 4, 6, 5], [], [2, 0, 1, 4, 6, 5], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []]
